# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'tracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtracker.proto\"5\n\x13RegisterPeerRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\r\n\x05\x66iles\x18\x02 \x03(\t\"\'\n\x14RegisterPeerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x11SearchFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"#\n\x12SearchFileResponse\x12\r\n\x05peers\x18\x01 \x03(\t2\x84\x01\n\x0eTrackerService\x12;\n\x0cRegisterPeer\x12\x14.RegisterPeerRequest\x1a\x15.RegisterPeerResponse\x12\x35\n\nSearchFile\x12\x12.SearchFileRequest\x1a\x13.SearchFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERPEERREQUEST']._serialized_start=17
  _globals['_REGISTERPEERREQUEST']._serialized_end=70
  _globals['_REGISTERPEERRESPONSE']._serialized_start=72
  _globals['_REGISTERPEERRESPONSE']._serialized_end=111
  _globals['_SEARCHFILEREQUEST']._serialized_start=113
  _globals['_SEARCHFILEREQUEST']._serialized_end=151
  _globals['_SEARCHFILERESPONSE']._serialized_start=153
  _globals['_SEARCHFILERESPONSE']._serialized_end=188
  _globals['_TRACKERSERVICE']._serialized_start=191
  _globals['_TRACKERSERVICE']._serialized_end=323
# @@protoc_insertion_point(module_scope)
