# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracker.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracker.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rtracker.proto\"5\n\x13RegisterPeerRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\r\n\x05\x66iles\x18\x02 \x03(\t\"\'\n\x14RegisterPeerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"&\n\x11SearchFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"#\n\x12SearchFileResponse\x12\r\n\x05peers\x18\x01 \x03(\t\"#\n\x10LeavePeerRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\"$\n\x11LeavePeerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb8\x01\n\x0eTrackerService\x12;\n\x0cRegisterPeer\x12\x14.RegisterPeerRequest\x1a\x15.RegisterPeerResponse\x12\x35\n\nSearchFile\x12\x12.SearchFileRequest\x1a\x13.SearchFileResponse\x12\x32\n\tLeavePeer\x12\x11.LeavePeerRequest\x1a\x12.LeavePeerResponseb\x06proto3')
)




_REGISTERPEERREQUEST = _descriptor.Descriptor(
  name='RegisterPeerRequest',
  full_name='RegisterPeerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='RegisterPeerRequest.peer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='files', full_name='RegisterPeerRequest.files', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=70,
)


_REGISTERPEERRESPONSE = _descriptor.Descriptor(
  name='RegisterPeerResponse',
  full_name='RegisterPeerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='RegisterPeerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=111,
)


_SEARCHFILEREQUEST = _descriptor.Descriptor(
  name='SearchFileRequest',
  full_name='SearchFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='SearchFileRequest.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=151,
)


_SEARCHFILERESPONSE = _descriptor.Descriptor(
  name='SearchFileResponse',
  full_name='SearchFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peers', full_name='SearchFileResponse.peers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=188,
)


_LEAVEPEERREQUEST = _descriptor.Descriptor(
  name='LeavePeerRequest',
  full_name='LeavePeerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='LeavePeerRequest.peer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=225,
)


_LEAVEPEERRESPONSE = _descriptor.Descriptor(
  name='LeavePeerResponse',
  full_name='LeavePeerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='LeavePeerResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=263,
)

DESCRIPTOR.message_types_by_name['RegisterPeerRequest'] = _REGISTERPEERREQUEST
DESCRIPTOR.message_types_by_name['RegisterPeerResponse'] = _REGISTERPEERRESPONSE
DESCRIPTOR.message_types_by_name['SearchFileRequest'] = _SEARCHFILEREQUEST
DESCRIPTOR.message_types_by_name['SearchFileResponse'] = _SEARCHFILERESPONSE
DESCRIPTOR.message_types_by_name['LeavePeerRequest'] = _LEAVEPEERREQUEST
DESCRIPTOR.message_types_by_name['LeavePeerResponse'] = _LEAVEPEERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterPeerRequest = _reflection.GeneratedProtocolMessageType('RegisterPeerRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERPEERREQUEST,
  __module__ = 'tracker_pb2'
  # @@protoc_insertion_point(class_scope:RegisterPeerRequest)
  ))
_sym_db.RegisterMessage(RegisterPeerRequest)

RegisterPeerResponse = _reflection.GeneratedProtocolMessageType('RegisterPeerResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERPEERRESPONSE,
  __module__ = 'tracker_pb2'
  # @@protoc_insertion_point(class_scope:RegisterPeerResponse)
  ))
_sym_db.RegisterMessage(RegisterPeerResponse)

SearchFileRequest = _reflection.GeneratedProtocolMessageType('SearchFileRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHFILEREQUEST,
  __module__ = 'tracker_pb2'
  # @@protoc_insertion_point(class_scope:SearchFileRequest)
  ))
_sym_db.RegisterMessage(SearchFileRequest)

SearchFileResponse = _reflection.GeneratedProtocolMessageType('SearchFileResponse', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHFILERESPONSE,
  __module__ = 'tracker_pb2'
  # @@protoc_insertion_point(class_scope:SearchFileResponse)
  ))
_sym_db.RegisterMessage(SearchFileResponse)

LeavePeerRequest = _reflection.GeneratedProtocolMessageType('LeavePeerRequest', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEPEERREQUEST,
  __module__ = 'tracker_pb2'
  # @@protoc_insertion_point(class_scope:LeavePeerRequest)
  ))
_sym_db.RegisterMessage(LeavePeerRequest)

LeavePeerResponse = _reflection.GeneratedProtocolMessageType('LeavePeerResponse', (_message.Message,), dict(
  DESCRIPTOR = _LEAVEPEERRESPONSE,
  __module__ = 'tracker_pb2'
  # @@protoc_insertion_point(class_scope:LeavePeerResponse)
  ))
_sym_db.RegisterMessage(LeavePeerResponse)



_TRACKERSERVICE = _descriptor.ServiceDescriptor(
  name='TrackerService',
  full_name='TrackerService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=266,
  serialized_end=450,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterPeer',
    full_name='TrackerService.RegisterPeer',
    index=0,
    containing_service=None,
    input_type=_REGISTERPEERREQUEST,
    output_type=_REGISTERPEERRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchFile',
    full_name='TrackerService.SearchFile',
    index=1,
    containing_service=None,
    input_type=_SEARCHFILEREQUEST,
    output_type=_SEARCHFILERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LeavePeer',
    full_name='TrackerService.LeavePeer',
    index=2,
    containing_service=None,
    input_type=_LEAVEPEERREQUEST,
    output_type=_LEAVEPEERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACKERSERVICE)

DESCRIPTOR.services_by_name['TrackerService'] = _TRACKERSERVICE

# @@protoc_insertion_point(module_scope)
